services:
  poker-sercive:
    build:
      context: ./java-sercive
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
    restart: unless-stopped
